### PR TITLE
Fix spawning zombie processes

### PR DESCRIPTION
**Pull request by abcdjdj**
Use the classic double forking method to avoid creating zombies
See here for more details - https://stackoverflow.com/a/16809886

Signed-off-by: Madhav Kanbur <abcdjdj@gmail.com>

### CODE REVIEW

**Comment by abcdjdj** [comment]
This should fix #42 , however I'm not sure how to deal with the True/False value returned by the original ExecuteCommand function. A quick grep shows that the return value is not used anywhere so I am a bit confused. Any inputs would be appreciated.

**Comment by abcdjdj** [comment]
Uh .. bump? @vkareh

**Comment by vkareh** [comment]
@flexiondotorg - this works well. Now when I close an app that was opened with mate-menu, I no longer get the `<defunct>` in my `ps`. Seems to be spawning processes correctly here.

@abcdjdj - I don't think we actually use the return value from `Execute`, but the sanest thing to do might be to return it just the same. I honestly don't think it's necessary though.

**Comment by abcdjdj** [comment]
So .. can this be merged now?

**Comment by flexiondotorg** [comment]
@abcdjdj Thank you very much for working on this! :heart:

**Pull request merged**
