### PR TITLE
Port to Python 3

### LINKED ISSUE #27: Migrate to Python 3
@flexiondotorg commented on [Mon Jul 24 2017](https://github.com/ubuntu-mate/mate-hud/issues/3)

MATE Menu is written using Python 3. It would be beneficial to migrate it to Python 3 so only one Python interpreter is present on the live image, therefore making the iso smaller.

### PR DESCRIPTION
**Pull request by vkareh**
This port depends on [libmate-menu](https://github.com/mate-desktop/mate-menus) being compiled with Python 3 support (which is possible after merging https://github.com/mate-desktop/mate-menus/pull/54)
Fixes #27

### CODE REVIEW

**Comment by vkareh** [comment]
@raveit65 - here, I've fixed the merge conflict. You should be able to build this with python3 and it will automatically use https://github.com/mate-desktop/mate-menus/pull/54

**Comment by raveit65** [comment]
Mate-menu doesn't start here.
```
[rave@mother ~]$ mate-menu 
Traceback (most recent call last):
  File "/usr/lib/mate-menu/mate-menu.py", line 33, in <module>
    import setproctitle
ModuleNotFoundError: No module named 'setproctitle'
```
It is really a lot of work/time to test this. As of latest commit in master i was forced to create a new tarball, where i can use this PR as patch for my rpm https://patch-diff.githubusercontent.com/raw/ubuntu-mate/mate-menu/pull/28.diff
Sorry, i don't complie /install packages by hand on my box. I always use a package-manager.
I suggest to create/tag a new tarball first from master to exclude issues by testers because of creation of own tarballs.

Well, compiling did work well.

**Comment by vkareh** [comment]
@raveit65 - seems like you need the `python3-setproctitle` library (that's what it's called in the ubuntu repos at least).

**Comment by vkareh** [comment]
@raveit65 - these seem to be the dependencies in ubuntu, just in case it's helpful for you. Note that this is for the python2 version, so most likely replace python-foo to python3-foo:
```bash
vkareh@lemu4:~ $ apt show mate-menu | grep ^Depends | sed -e s/,/\\n/g 
Depends: python-pkg-resources
 python:any (<< 2.8)
 python:any (>= 2.7.5-5~)
 dconf-gsettings-backend | gsettings-backend
 gir1.2-mate-desktop (>= 1.18.0)
 gir1.2-mate-panel (>= 1.18)
 gir1.2-gtk-3.0
 gvfs-bin
 mate-menus (>= 1.18)
 mozo | menulibre
 python (>= 2.4)
 python (<< 3)
 python-configobj
 python-mate-menu
 python-setproctitle
 python-xdg
 python-xlib
 xdg-utils
 libglib2.0-bin
```

**Comment by raveit65** [comment]
Ok, i changed runtime requires to 
Requires:       mate-menus
Requires:       mozo
Requires:       python3-configobj
Requires:       python3-gobject
Requires:       pyxdg
Requires:       python3-xlib
Requires:       python3-setproctitle
Requires:       beesu
Requires:       mate-panel

Not sure if pyxdg the right package for pyton3.
Now i got this error:
[rave@mother ~]$ mate-menu
Unable to load places plugin :-(
Unable to load system_management plugin :-(
Unable to load applications plugin :-(
Binding to Hot Key: Super_L

In app itself it complains about missing modul 
No modul named uniddecode

what ever this is...?

**Comment by raveit65** [comment]
Ok, i need python3-pyxdg package  but this is already installed.

**Comment by raveit65** [comment]
\o/  python3-unidecode was missing.
Now gui looks again complete and i can test.
For this reason i don't like python as i don't know  to find out which runtime requires are needed in a SPEC file.

**Comment by raveit65** [comment]
Omg, mozo needs ported to python3 too :-)
If i execute 'edit menus' from right-click menu i get another modul error.
```
[rave@mother ~]$ mate-menu
Removing file : /home/rave/.config/mate-menu/-usr-share-git-gui-lib-git-gui.ico
Binding to Hot Key: Super_L
/usr/lib/mate-menu/mate-menu-config.py
mozo
Traceback (most recent call last):
  File "/usr/bin/mozo", line 22, in <module>
    from Mozo.MainWindow import MainWindow
  File "/usr/lib/python2.7/site-packages/Mozo/MainWindow.py", line 19, in <module>
    import matemenu
ImportError: No module named matemenu
```
```
[rave@mother ~]$ mozo
Traceback (most recent call last):
  File "/usr/bin/mozo", line 22, in <module>
    from Mozo.MainWindow import MainWindow
  File "/usr/lib/python2.7/site-packages/Mozo/MainWindow.py", line 19, in <module>
    import matemenu
ImportError: No module named matemenu

```

**Comment by vkareh** [comment]
yeah I don't understand a lot of how python manages dependencies. The `setup.py` file lists `unidecode` as a dependency, but it only fails during runtime, rather than during build. Also, I don't even have that package installed, so I don't know which other library is providing it 😕❗️❓

I'm glad you got it working! 😄

**Comment by vkareh** [comment]
Yeah, I expected that... no fun having to run both python versions of matemenu alongside each other... I'm forking mozo now :)

**Comment by raveit65** [comment]
@vkareh 
I have your python3 port running with https://github.com/ubuntu-mate/mate-menu/pull/38
Only minimal adjustments is needed.
I dropped those lines from your patch and everything works. This is already done in other PR.
```
--- mate_menu/plugins/applications.py
+++ mate_menu/plugins/applications.py
@@ -1570,7 +1570,7 @@ def buildApplicationList( self ):
         def find_applications_recursively(app_list, directory, catName):
             for item in directory.get_contents():
                 if item.get_type() == matemenu.TYPE_ENTRY:
-                    #print "=======>>> " + str(item.name) + " = " + str(catName)
+                    #print("=======>>> " + str(item.name) + " = " + str(catName))
                     app_list.append( { "entry": item, "category": catName } )
                 elif item.get_type() == matemenu.TYPE_DIRECTORY:
                     find_applications_recursively(app_list, item, catName)
@@ -1591,7 +1591,7 @@ def find_applications_recursively(app_list, directory, catName):
                             newApplicationsList.append( { "entry": item, "category": entry.name } )
                 #elif entry.get_type() == matemenu.TYPE_ENTRY:
                 #       if not (entry.get_is_excluded() or entry.get_is_nodisplay()):
-                #               print "=======>>> " + item.name + " = top level"
+                #               print("=======>>> " + item.name + " = top level")
                 #               newApplicationsList.append( { "entry": item, "category": "" } )
 
         return newApplicationsList
```

**Comment by raveit65** [comment]
@vkareh 
Can you rebase against master please?
Or should we use https://github.com/ubuntu-mate/mate-menu/pull/36 for python3 support?

**Comment by vkareh** [comment]
@raveit65 - I just rebased against `master`. I compared the conflicted diff and this new one and it looks fine now from my side, but please test to make sure I didn't override anything here.

**Comment by raveit65** [comment]
yeap, it works fine in a quick test.

@flexiondotorg 
Can this be reviewed please?

**Comment by flexiondotorg** [comment]
Thanks for working on this! :heart:

**Pull request merged**
